Connecting nikoskar@at-database.ad.bcm.edu:3306
  0%|                                                 | 0/5100 [00:00<?, ?it/s]  0%|                                                 | 0/5100 [00:07<?, ?it/s]
Traceback (most recent call last):
  File "/project/renderstim/notebooks/generate.py", line 5, in <module>
    RenderedScenes().populate(key, display_progress=True, reserve_jobs=True)
  File "/usr/local/lib/python3.9/dist-packages/datajoint/autopopulate.py", line 159, in populate
    make(dict(key))
  File "/project/renderstim/schema/templates/rendered_scenes.py", line 79, in make
    self.insert1(key)
  File "/usr/local/lib/python3.9/dist-packages/datajoint/table.py", line 175, in insert1
    self.insert((row,), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/datajoint/table.py", line 336, in insert
    rows = list(make_row_to_insert(row) for row in rows)
  File "/usr/local/lib/python3.9/dist-packages/datajoint/table.py", line 336, in <genexpr>
    rows = list(make_row_to_insert(row) for row in rows)
  File "/usr/local/lib/python3.9/dist-packages/datajoint/table.py", line 306, in make_row_to_insert
    attributes = [make_placeholder(name, row[name]) for name in heading if name in row]
  File "/usr/local/lib/python3.9/dist-packages/datajoint/table.py", line 306, in <listcomp>
    attributes = [make_placeholder(name, row[name]) for name in heading if name in row]
  File "/usr/local/lib/python3.9/dist-packages/datajoint/table.py", line 271, in make_placeholder
    value = blob.pack(value)
  File "/usr/local/lib/python3.9/dist-packages/datajoint/blob.py", line 458, in pack
    return Blob().pack(obj, compress=compress)
  File "/usr/local/lib/python3.9/dist-packages/datajoint/blob.py", line 444, in pack
    blob = self.pack_blob(obj)  # this may reset the protocol and must precede protocol evaluation
  File "/usr/local/lib/python3.9/dist-packages/datajoint/blob.py", line 153, in pack_blob
    self.set_dj0()
  File "/usr/local/lib/python3.9/dist-packages/datajoint/blob.py", line 76, in set_dj0
    raise DataJointError("""v0.12+ python native blobs disabled.
datajoint.errors.DataJointError: v0.12+ python native blobs disabled.
                See also: https://github.com/datajoint/datajoint-python#python-native-blobs
Error: Not freed memory blocks: 1, total unfreed memory 0.001259 MB
